# -*- coding: utf-8 -*-
"""MMAE Calculators

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BGoPUIQR3pw7iGzLgQElYx0r-gbRrqyb
"""

#Dot product
import numpy
import numpy as np
import math
A=np.array([0,0,0,]) #Replace these values
B=np.array([0,0,0,]) #Replace these values
G=A@B
print('the dot product between A and B is',G)

#angle between vectors
import numpy
import numpy as np
import math
A=np.array([1,0,0,]) #Replace these values
B=np.array([0,1,0,]) #Replace these values
L = np.array(numpy.cross(A,B))
degx=numpy.arccos(L[0]/(math.sqrt((L[0]**2)+(L[1]**2)+(L[2]**2))))
degy=numpy.arccos(L[1]/(math.sqrt((L[0]**2)+(L[1]**2)+(L[2]**2))))
degz=numpy.arccos(L[2]/(math.sqrt((L[0]**2)+(L[1]**2)+(L[2]**2))))
print("The angle on x-axis is:",degx)
print("The angle on y-axis is:",degy)
print("The angle on z-axis is:",degz)

#Unit Vector
import numpy
import numpy as np
import math
A=np.array([1,0,0,]) #Replace these values
B=np.array([0,1,0,]) #Replace these values
H=(np.cross(A,B)/np.linalg.norm(np.cross(A,B)))
print(np.cross(A,B))
print('The unit vector of A and B is', H)

#Magnitude
import numpy
import numpy as np
import math
A=np.array([1,0,0,]) #Replace these values
B=np.array([0,1,0,]) #Replace these values
H=(np.linalg.norm(A))
print('The Magnitude is', H)

#System of equations
import numpy
import numpy as np
import math
A= np.array([[2,0.7],[-1.2,2.7]]) #this is where the LHS of equal sign equation goes.
B= np.array([[2],[-17]]) #this is where the RHS side of equations go
v = np.linalg.inv(A)@B
print(v) #prints an array, the first being the solution of the first variable, and so on

